version: 0.4.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: Ve.Metrics.StatsDClient.*.nupkg
  name: NuGet Package
cache:
- packages -> **\packages.config
deploy:
  provider: NuGet
  api_key:
    secure: WgNq9OREiVbfGKhKjoleAjb7UNErvzlqPyv3C5w5dEtsw90MtMyp/EIfpk+g3HRF
  skip_symbols: false
  artifact: /.*\.nupkg/
